---
title: "Methode"
subtitle: "Überblick Open-Access-Metadaten-Schnelltest"
pkgdown:
    as_is:true
bibliography: metacheck.bib
csl: apa.csl
---

<!-- NOTE this has to stay in sync with methodology.Rmd -->

Umfangreiche Metadaten sichern die Auffindbarkeit und Nachnutzung von
Open-Access (OA) Artikeln. 
Aus diesem Grunde ist die Überprüfung der Metadaten ein wesentlicher Workflow-Bestandteil beim Umgang mit OA-Publikationsgebühren und Transformationsverträgen [@Geschuhn_2017; @Marques_2019].

Der Open-Access-Metadaten-Schnelltest ermöglicht die automatische Überprüfung der Metadatenqualität von OA-Zeitschriftenartikeln.
Er richtet sich in erster Linie an Bibliotheken und wissenschaftliche Informationseinrichtungen, die Open-Access-Publikationskosten verwalten. 

Im Mittelpunkt der Überprüfung des Open-Access-Metadaten-Schnelltests stehen die Metadaten der DOI-Registrierungsagentur [Crossref](https://www.crossref.org/). 
Crossref wird von den meisten wissenschaftlichen Verlagen verwendet [@Hendricks_2020] und auch im Kontext von Publikationsfonds und Transformationsverträgen werden die meisten DOIs für Open-Access-Artikel über Crossref registriert [@Jahn_2016; @Pieper_2018]. 
Crossref-Metadatenservices werden zudem umfangreich in Forschung und Praxis zum Auffinden von Open-Access-Artikeln genutzt, z.B. durch den Open-Access-Discovery-Service [Unpaywall](https://unpaywall.org/) [@Piwowar_2018], der eine wesentliche Quelle des deutschen [Open Access Monitor](https://open-access-monitor.de/#/home) ist.

Der Open-Access-Metadaten-Schnelltest nutzt [Crossref Metadata Plus](https://www.crossref.org/services/metadata-retrieval/metadata-plus/). 
Ein Rahmenvertrag sichert einen priorisierten und hochperformanten Zugang zu den Crossref-Schnittstellen.

<div class="alert alert-warning" role="alert">
`r metacheck::mc_long_docs_string("disclaimer_fe.md", lang = "de")`
</div>

## Vorgehen

Der quelloffene Open-Access-Metadaten-Schnelltest erlaubt die umfangreiche Überprüfung von bis zu 1.000 DOIs pro Bericht und liefert ein Untersuchungsergebnis innerhalb von 45 Minuten per Email. 
Im Anhang der Ergebnis-Email befindet sich zudem ein umfassender Datenanhang als Exceltabelle.

## Vorabprüfung

Vor dem eigentlichen Metadatentest findet eine umfangreiche Vorabprüfung statt. 
DOIs werden von der weiteren Analyse ausgeschlossen wenn:

- sie mehrfach vorkommen,
- sie das Limit von ggw. 1000 DOIs überschreiten,
- sie beim Link Resolver doi.org nicht bekannt sind,
- sie nicht von Crossref registriert wurden,
- für sie keine Metadaten bei Crossref vorliegen oder
- es sich dabei nicht um einen Zeitschriftenartikel handelt.

Weitere Details in `metacheck::pretest()`.

## Testergebnis

Das Testergebnis umfasst folgende Metadatenkriterien:

### Überblick: Crossref-Metadaten

Der Abschnitt zeigt einen tabellarischen Überblick der Überprüfung. 
Nur Publikationen mit Metadaten in Crossref werden berücksichtigt.
Es werden absolute und relative Häufigkeiten dargestellt.

Untersucht wurden:

- Verfügbarkeit von Creative-Commons-Lizenzen (CC License)
- Verfügbarkeit von regelkonformen CC-Lizenzen (Compliant CC)
- Unterstützung von Versionen für das Text- und Data-Mining (TDM) (TDM Support)
- Verknüpfung zwischen Publikationen und Förderinformationen (Funder info)
- Verknüpfung zwischen Publikationen und ORCID
- Unterstützung weitere offener Metadaten ([Open Abstracts](https://i4oa.org/) und [Open Citations](https://i4oc.org/))

### Creative-Commons-Lizenzen

Offene Lizenzen sind wesentlich, um den Zugang und die Nachnutzung von Open-Access-Artikeln unter bestimmten Bedingungen zu regeln. 
Einschlägig sind die Creative-Commons-Lizenzen (CC-Lizenzen) (siehe Überblick des
[Bundesministeriums für Bildung und Forschung](https://www.bildung-forschung.digital/de/lizenzvertrag-und-offene-lizenzen-2650.html)).

Der Open-Access-Metadaten-Schnelltest normalisiert die Varianten der Creative-Commons-Lizenzen und untersucht, ob Creative-Commons-Lizenzen in den Metadaten regelkonform erfasst sind.

#### Lizenzbedingungen

Die tabellarische Übersicht zeigt die Häufigkeit von CC-Varianten an. 
CC-BY ist sowohl in den [DEAL-Verträgen](https://www.projekt-deal.de/) als auch beim [DFG-Programm Open-Access-Publikationskosten](https://www.dfg.de/foerderung/programme/infrastruktur/lis/lis_foerderangebote/open_access_publikationskosten/index.html) der präferierte Lizenztyp.
`NA` bedeutet, dass keine Lizeninformation in den Crossref-Metadaten verfügbar ist.

#### Ergebnis Compliance Check

Die Tabelle zeigt die Anzahl und den Anteil **regelkonformer CC-Lizenzinformationen** laut dem HOAD-Algorithmus. 
Eine Lizenzinformation ist genau dann regelkonform, wenn

- es sich um eine Creative-Commons-Standardlizenz handelt,
- die CC-Lizenz sich auf die Verlagsversion, die sogenannte "version-of-record" bezieht,
- und die CC-Lizenz mit Erscheinen ohne zeitlichen Verzug gültig ist (Ausschluss von delayed OA)

Wir haben festgestellt, dass Verlage zwar immer häufiger CC-Lizenzen in den Crossref-Metadaten verzeichnen, einige allerdings die Lizenzinformation nur unvollständig beschreiben. 
Dies kann Auswirkungen auf die automatisierte Auffindbarkeit von Open-Access-Artikeln haben. 

**Bei Problemen empfehlen wir daher, mit dem Verlag in Kontakt zu treten.**

Mehr Hintergrundinformationen zur Überprüfung von Lizenzinformationen in Crossref im Kontext von OA-Transformationsverträgen finden Sie bei @Voigt_2020.

### Text and Data Mining (TDM)

Der nächste Abschnitt bietet einen Überblick, welche Dateiformate,
ausgedrückt als [MIME Type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types), für das Text- und Data-Mining (TDM) unterstützt werden. 
Grundsätzlich kann je Artikel mehr als ein Format angeboten werden. 
Wir empfehlen, dass Verlage neben PDF-Dateien auch strukturierte XML-Volltexte verfügbar machen, um die automatisierte Nachnutzung zu erleichtern.

Die prozentualen Anteile in der Tabelle beziehen sich auf alle getesteten Artikel mit Crossref-Metadaten. 

### Förderinformationen

Es gibt ein großes Interesse, den Förderkontext von Open-Access-Artikeln zu
erheben. 
Einige, aber nicht alle Verlage nutzen Crossref, um den Förderinformationen zu teilen. 
Der Open-Access-Metadaten-Schnelltest zeigt an, bei wie vielen Artikeln Crossref mindestens eine Forschungsförderung verzeichnet.

Bitte beachten Sie, dass aufgrund der unvollständigen Abdeckung Crossref (noch) nicht geeignet ist für umfangreiche Analysen des Förderkontexts von Publikationen.

## Datenanhang

Beigefügt zur Email befindet sich ein Excel-Spreadsheet mit Metadaten auf Artikelebene für weitere Analysen. Es umfasst folgende Datenblätter:

- `cr_overview`: Überblick  
- `cc_license_check`: Detailauswertung Lizenzüberprüfung
- `tdm`: Detailauswertung Volltextlinks und TDM
- `funder_info`: Förderinformationen lt. Crossref
- `pretest`: Ergebnisse der Vorabprüfung

## Literatur
