---
title: "Methodology"
subtitle: "Overview of metacheck"
pkgdown:
    as_is:true
bibliography: metacheck.bib
csl: apa.csl
---

Rich metadata ensure that open access articles can be found and re-used. Therefore, negotiating and monitoring  metadata elements for open access articles is critical according to workflow recommendations for transformative agreements [@Geschuhn_2017; @Marques_2019; @Borrego_2020].

metacheck allows you to automatically validate the metadata richness and quality of publisher-provided metadata for open access journal articles. The tool mainly targets libraries and consortia that manage open access publishing funds and transformative agreements.

metacheck focuses on the DOI registration agency [Crossref](https://www.crossref.org/). Crossref is used by all major publishers [@Hendricks_2020], and also in the context of open access publishing funds and transformative agreements most articles have Crossref-registered DOIs [@Jahn_2016; @Pieper_2018]. Crossref is also a key data source for leading open access discovery tools like [Unpaywall](https://unpaywall.org/) [@Piwowar_2018].

metacheck uses [Crossref Metadata Plus](https://www.crossref.org/services/metadata-retrieval/metadata-plus/). A service-level agreement ensures supported access to the Crossref REST API.

**Please note that while metacheck supports your workflows to check OA metadata deposited by publishers, it cannot conclusively check funding eligibility of OA publications. Please consult the funding conditions of the respective funder.**

## How to use metacheck

You can check up to 1,000 DOIs at once using this freely available tool. We'll run a couple of checks and you can expect an email report within 45 minutes. With this email, you also receive a comprehensive Excel spreadsheet with article-level metadata. 

## Pretest

In a first step, we do some preliminary checks. DOIs will be excluded, if

- duplicated
- the limit of 1,000 DOIs is exceeded
- DOIs do not resolve to doi.org
- DOIs were not registered with Crossref
- no Crossref metadata was available
- publication is not of type `journal-article`

See <https://subugoe.github.io/metacheck/reference/pretest.html> for more details.

## Test results

Test results are structured as follows:

### Overview: Crossref metadata

The first table presents an overview of the test results, showing absolute and relative number. 

We checked the following Crossref metadata elements:

- Availability of a Creative Commons Licenses (CC License)
- Availability of compliant Creative Commons Licenses (Compliant CC)
- TDM Support 
- Funder information (Funder info)
- ORCID
- [Open Abstracts](https://i4oa.org/) 
- [Open Citations](https://i4oc.org/)

### Creative Commons Licenses

Open content licenses are essential to govern access and re-use to open access journal articles. 

metacheck normalizes Creative Commons licenses and map them to the different variants in use like CC BY. We also check, if license statements are compliant.

#### Overview Licensing

This table shows the number and percentage by Creative Commons variant. Many research funders recommend CC-BY, in particular those supporting the [Plan S Principles](https://www.coalition-s.org/plan_s_principles/). `NA` represents articles where no licence metadata was found. 

#### Results Compliance Check

The next table presents the number and percentage of articles with compliant license metadata. We consider license metadata as compliant, if and only if 

- the license URL represents a Creative Commons license URL
- the Creative Commons license refers to the publisher version, the so-called "version-of-record"
- the Creative Commons license came into effect at the date of publication (exclusion of delayed OA).

We noted that while more and more publishers do provide Creative Commons license metadata through Crossref, some metadata is still incomplete. This can negatively affect the discovery and re-use of open access articles. 

**If you observe license metadata issues, we strongly encourage you to contact the publisher**

### Text and Data Mining (TDM)

Next, the report presents which file formats (MIME Type) are supported for text and data mining (TDM). Please note that Crossref metadata can include more than one format for each DOI. We recommend that publishers do not only provide PDF files for TDM purposes, but also XML to promote automated re-use.

The percentage share refers to the total number of checked DOIs.

### Funding Information

The funding context of research articles becomes more and more important in open access monitoring. A growing number of publishers use Crossref to share such information. This table gives an overview over the most frequent funders per DOI, as per Crossref metadata. Crossref metadata can include more than one funder for each DOI.

The percentage share refers to the total number of checked DOIs.

### Attachment

An attached Excel-Spreadsheet allows you to build on our analysis. It contains the following sheets with article-level metadata:

- `cr_overview`: Overview  
- `cc_license_check`: License metadata 
- `tdm`: Full-text links for Text and Data Mining (TDM)
- `funder_info`: Funder information
- `pretest`: Pre-test

## References
